context:
  version: "0.8.0"

package:
  name: lelwel
  version: ${{ version }}

source:
  url: https://github.com/0x2a-42/lelwel/archive/v${{ version }}.tar.gz
  sha256: 4d4fed88fc6f7b1262f4c10d50ba97b86120beb2db32112b4e9f33e7f166ea56

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - llw --help

about:
  license: Apache-2.0 AND MIT
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: Resilient LL(1) parser generator for Rust
  homepage: https://github.com/0x2a-42/lelwel
  repository: https://github.com/0x2a-42/lelwel

extra:
  recipe-maintainers:
    - danielnachun
