context:
  version: 0.6.4

package:
  name: lelwel
  version: ${{ version }}

source:
  url: https://github.com/0x2a-42/lelwel/archive/v${{ version }}.tar.gz
  sha256: 9b684ce08e82c4074d19620e6494218c8808bcb017582949eb638ca84b554f6c

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - llw --help

about:
  license: Apache-2.0 AND MIT
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: Resilient LL(1) parser generator for Rust
  homepage: https://github.com/0x2a-42/lelwel
  repository: https://github.com/0x2a-42/lelwel

extra:
  recipe-maintainers:
    - danielnachun
