context:
  version: "0.9.1"

package:
  name: lelwel
  version: ${{ version }}

source:
  url: https://github.com/0x2a-42/lelwel/archive/v${{ version }}.tar.gz
  sha256: 5e8d56938f5e9861e2e6b1119258f5582e944c83c3092c4837ea41a157e673c7

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - llw --help

about:
  license: Apache-2.0 AND MIT
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: Resilient LL(1) parser generator for Rust
  homepage: https://github.com/0x2a-42/lelwel
  repository: https://github.com/0x2a-42/lelwel

extra:
  recipe-maintainers:
    - danielnachun
